import React from 'react';
// import Navigation from "../components/Navigation";

const About = () => {
    return (
        <>
            {/* <Navigation /> */}
           


           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, praesentium. Quidem dolores aperiam mollitia quae quod earum odio nesciunt alias obcaecati itaque fugit similique sequi saepe minima voluptate, quibusdam reiciendis qui. Voluptates soluta totam fugiat deleniti voluptate laboriosam odio sit enim porro inventore voluptatum non, accusantium quia a eveniet doloremque exercitationem? Consequuntur hic repellat nemo quisquam mollitia delectus id, voluptatum doloribus commodi ullam laborum dolores in? Ullam quisquam eius voluptatum sint, excepturi rerum. Iusto beatae cupiditate odio aliquid in eos sint. Excepturi, corporis. Fugit tempore eius quae eligendi repudiandae sed repellendus a. Delectus expedita quidem exercitationem natus ex quae eveniet asperiores enim laboriosam qui inventore similique laudantium adipisci fugiat mollitia necessitatibus, incidunt, nulla in voluptates debitis, perspiciatis voluptatum quis sint. Quidem magnam fugit quisquam ipsa quibusdam provident veniam voluptatibus adipisci eius non officia fuga culpa recusandae earum, laboriosam cum obcaecati, quos vero repellendus. Voluptatem suscipit perferendis, quisquam consequuntur corrupti ullam alias tempore magni voluptatibus repellendus commodi eius dignissimos eos nobis non provident voluptates iste maiores nam, optio ad tenetur! Officia repudiandae dolor impedit. Dolorem commodi quas perferendis rerum error. Eos cum, debitis omnis quo aperiam quod distinctio aliquid, suscipit molestiae ea dignissimos non repellendus maiores blanditiis odio necessitatibus fuga fugit.</p>
           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, praesentium. Quidem dolores aperiam mollitia quae quod earum odio nesciunt alias obcaecati itaque fugit similique sequi saepe minima voluptate, quibusdam reiciendis qui. Voluptates soluta totam fugiat deleniti voluptate laboriosam odio sit enim porro inventore voluptatum non, accusantium quia a eveniet doloremque exercitationem? Consequuntur hic repellat nemo quisquam mollitia delectus id, voluptatum doloribus commodi ullam laborum dolores in? Ullam quisquam eius voluptatum sint, excepturi rerum. Iusto beatae cupiditate odio aliquid in eos sint. Excepturi, corporis. Fugit tempore eius quae eligendi repudiandae sed repellendus a. Delectus expedita quidem exercitationem natus ex quae eveniet asperiores enim laboriosam qui inventore similique laudantium adipisci fugiat mollitia necessitatibus, incidunt, nulla in voluptates debitis, perspiciatis voluptatum quis sint. Quidem magnam fugit quisquam ipsa quibusdam provident veniam voluptatibus adipisci eius non officia fuga culpa recusandae earum, laboriosam cum obcaecati, quos vero repellendus. Voluptatem suscipit perferendis, quisquam consequuntur corrupti ullam alias tempore magni voluptatibus repellendus commodi eius dignissimos eos nobis non provident voluptates iste maiores nam, optio ad tenetur! Officia repudiandae dolor impedit. Dolorem commodi quas perferendis rerum error. Eos cum, debitis omnis quo aperiam quod distinctio aliquid, suscipit molestiae ea dignissimos non repellendus maiores blanditiis odio necessitatibus fuga fugit.</p>

           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur, praesentium. Quidem dolores aperiam mollitia quae quod earum odio nesciunt alias obcaecati itaque fugit similique sequi saepe minima voluptate, quibusdam reiciendis qui. Voluptates soluta totam fugiat deleniti voluptate laboriosam odio sit enim porro inventore voluptatum non, accusantium quia a eveniet doloremque exercitationem? Consequuntur hic repellat nemo quisquam mollitia delectus id, voluptatum doloribus commodi ullam laborum dolores in? Ullam quisquam eius voluptatum sint, excepturi rerum. Iusto beatae cupiditate odio aliquid in eos sint. Excepturi, corporis. Fugit tempore eius quae eligendi repudiandae sed repellendus a. Delectus expedita quidem exercitationem natus ex quae eveniet asperiores enim laboriosam qui inventore similique laudantium adipisci fugiat mollitia necessitatibus, incidunt, nulla in voluptates debitis, perspiciatis voluptatum quis sint. Quidem magnam fugit quisquam ipsa quibusdam provident veniam voluptatibus adipisci eius non officia fuga culpa recusandae earum, laboriosam cum obcaecati, quos vero repellendus. Voluptatem suscipit perferendis, quisquam consequuntur corrupti ullam alias tempore magni voluptatibus repellendus commodi eius dignissimos eos nobis non provident voluptates iste maiores nam, optio ad tenetur! Officia repudiandae dolor impedit. Dolorem commodi quas perferendis rerum error. Eos cum, debitis omnis quo aperiam quod distinctio aliquid, suscipit molestiae ea dignissimos non repellendus maiores blanditiis odio necessitatibus fuga fugit.</p>
        </>
    );
};

export default About;